package Entities.HelperClasses;

public enum JobPosition {
    WAREHOUSE_MANAGER,
    FORKLIFT_OPERATOR,
    INVENTORY_CONTROL_SPECIALIST,
    SHIPPING_AND_RECEIVING_CLERK,
    ORDER_PICKER_PACKER,
    WAREHOUSE_CLERK,
    LOADER,
    STOCKER,
    WAREHOUSE_PACKER,
    MATERIAL_HANDLER,
    QUALITY_CONTROL_INSPECTOR,
    WAREHOUSE_SUPERVISOR;
}
